### PR TITLE
Differentiate a tap from swipe

### PR DESCRIPTION
**Pull request by sandy-adi**

### CODE REVIEW

**Comment by sandy-adi** [comment]
@irae can you please take a look?

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by sandy-adi** [comment]
@yahoocla agreed to the CLA

**Comment by irae** [comment]
This might be more suited to be fixed on `vendor/zynga`. Could you please double check if the same fix is possible there? Thanks.

**Comment by irae** [comment]
Thanks for your contribution!

**Pull request merged**
