### PR TITLE
Update to React 14

### PR DESCRIPTION
**Pull request by mayank-hey**
@irae Please review
Summary of changes
- Using react-dom for rendering
- Removing deprecated getDOMNode calls
- Bumping version after updating peer dependency

Ref: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#upgrade-guide

### CODE REVIEW

**Comment by irae** [comment]
The Yahoo CLA bot didn't comment yet. This comment will probably trigger it.

I can't run `npm run dev` anymore, it has issues with the version you added of `react-hammerjs`. On node 0.10 it errors on ./emptyFunction, on node 0.12 it complains there is no Object.assign and on node v4.1.1 the server crashes with buffer exceptions. Can you clarify which version are you running the library? It used to be compatible with node 0.10 because that is still the stable version Yahoo uses internally.

Thanks

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by irae** [comment]
OK, I figured out. I will merge your PR but I will fix it before pushing to NPM.

Thanks very much for the time spent fixing this. I will ping you the commit that finalizes the PR here once I am done, for your reference.

**Comment by irae** [comment]
This is the commit: https://github.com/yahoo/scrollable/commit/aaf302d04b0813835d2c3c858710c8ee4e9bf7bb

If possible, can you test your application against scrollable@master before I make a push to npm?

**Pull request merged**
