### PR TITLE
Revert change made to distinguish between tap and swipe

### PR DESCRIPTION
**Pull request by sandy-adi**

### CODE REVIEW

**Comment by irae** [comment]
why?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by sandy-adi** [comment]
So, in our functional tests we use the scroll test helper, this is not the same as a user swipe which also causes touchMove event which is where we populate the `__positions`. Since touchMove doesn't happen  in this case this will not work in functional tests :disappointed: 

Do you have any ideas?

**Comment by irae** [comment]
I will need to take a deeper look. Also, remember this is public github, and there is no "functional tests" here. Maybe the test helper, which is actually provided by this repo, needs to actually simulate some touch moves or call "doTouchMove" directly to emulate better.

**Pull request merged**
